### ISSUE TITLE
/lib/model/nms/src/nms_cuda.c missing

### ISSUE THREAD

**Issue by RolandAndrews** [luzhang16/AR-CNN#21]
Hello, 
Thank you for your very interesting paper. 
I tried to test your code however I have an error due to the call of "'src/nms_cuda.c" in /lib/model/nms/build.py line 16. The issue is that /lib/model/nms/src/nms_cuda.c does not exist.
I am doing something wrong ?

Thank you

**Comment by Shivam067** [comment]
> Hello, Thank you for your very interesting paper. I tried to test your code however I have an error due to the call of "'src/nms_cuda.c" in /lib/model/nms/build.py line 16. The issue is that /lib/model/nms/src/nms_cuda.c does not exist. I am doing something wrong ?
> 
> Thank you

Hello,
I am facing the same issue. Can you tell me how did you solve it?

Thank you
