### ISSUE TITLE
开源学习

### ISSUE THREAD

**Issue by SGQ-py** [luzhang16/AR-CNN#6]
Hello, may I ask whether your source code can be open source? This paper of yours has made a great contribution to CV, I want to learn it, is it convenient?

**Comment by luzhang16** [comment]
非常高兴您对我们的工作感兴趣，请参考这个链接 #4 
btw，文章不是CVPR的~

**Comment by SGQ-py** [comment]
尊敬的Lu Zhang博士：
      您好！
      感谢您的来信，我感到十分激动！嗯，之前是我搞错了，这里深表歉意。它是发表在ICCV 2019上的，再次谢谢您的回复。


                                                                                                                                                                                                        2020.08.03
                                                                                                                                                                                                           SGQ-py


| |
wxxd
|
|
17806259143@163.com
|
签名由网易邮箱大师定制
在2020年8月1日 13:07，Lu Zhang<notifications@github.com> 写道：

非常高兴您对我们的工作感兴趣，请参考这个链接 #4
btw，文章不是CVPR的~

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
