### ISSUE TITLE
Sample protocol?

### ISSUE THREAD

**Issue by echoofluoc** [luzhang16/AR-CNN#9]
Thanks for your work and code! 

A pity you don't share the training script, I want to know What the protocol you use to divide the training data into 8892 pairs of images(according to the AR-CNN/splits/trainval.txt) which you didn't describe in your paper? Is it similar to the sample/sanitized protocol described in MSDS-RCNN?

**Comment by luzhang16** [comment]
Hi, thank you for your attention! We sampled images with 2-frame skips in the training video. Images that do not contain "person" are ignored.
